question_data =[
        {"type": "boolean",
         "difficulty": "easy",
         "category": "Entertainment: Video Games",
         "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "The song &quot;Megalovania&quot; by Toby Fox made its third appearence in the 2015 RPG &quot;Undertale&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "In &quot;Resident Evil&quot;, only Chris has access to the grenade launcher.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In &quot;Super Mario 64&quot;, collecting 100 coins on a level will give you a 1-UP.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Codemasters is the developer of the Gran Turismo series.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
         "question": "The names of Roxas&#039;s Keyblades in Kingdom Hearts are &quot;Oathkeeper&quot; and &quot;Oblivion&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Rollercoaster Tycoon 1 and 2 were developed by Chris Sawyer.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "The game series &quot;Titanfall&quot; runs on the Unreal Engine.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "&quot;Half-Life 2&quot; runs on the Source Engine.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In &quot;Need for Speed: Porsche Unleashed&quot;, the player can only drive cars manufactured by Porsche.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "The main character in the &quot;Half-Life&quot; franchise is named Morgan Freeman.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
         "question": "Unturned originally started as a Roblox game.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Rebecca Chambers does not appear in any Resident Evil except for the original Resident Evil and the Gamecube remake.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
         "question": "In &quot;Portal 2&quot;, Cave Johnson started out Aperture Science as a shower curtain company.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Gordon Freeman, the protagonist of &quot;Half-Life&quot;, is said to have once had a ponytail.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "The edutainment video game series character, Carmen Sandiego, is partially named after Brazilian actress, Carmen Miranda.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "In the Disgaea series, any character can equip any weapon.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
         "question": "Danganronpa 2: Goodbye Despair featured all of the surviving students from the first game.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "The name of the main character of the video game &quot;The Legend of Zelda&quot;, is Zelda.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "&quot;Undertale&quot; is an RPG created by Toby Fox and released in 2015.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "The Kerbol System (from Kerbal Space Program) includes a Saturn analogue.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "In World of Warcraft lore, Thrall is the original wielder of &quot;Doomhammer&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "There are 6 legendary cards in &quot;Clash Royale&quot;.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "Fortnite was originally intended to be a horror game.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
         "question": "Super Mario and Paarthurnax (Skyrim) are voiced by the same actor.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "The Sniper&#039;s SMG in Team Fortress 2, was originally intended to be the Scout&#039;s primary weapon.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Big the Cat is a playable character in &quot;Sonic Generations&quot;.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "The shotgun appears in every numbered Resident Evil game.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game&#039;s plot.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Nintendo&#039;s Luigi was originally just called Green Mario?", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
         "question": "In &quot;The Sims&quot; series, the most members in a household you can have is 8.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Luigi is taller than Mario?", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "The Ace Attorney trilogy was suppose to end with &quot;Phoenix Wright: Ace Attorney &minus; Trials and Tribulations&quot; as its final game.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Super Mario Bros. was the first video game ever created.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In the Monster Hunter Series, it is possible to capture Elder Dragons.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In the Super Mario series, the character Pauline is a Princess like Princess Peach.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
         "question": "McCree from Overwatch originally started as a character that was going to appear in a scrapped Starcraft game.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "In &quot;League of Legends&quot;, there exists four different types of Dragon.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "As of February 2019, the &quot;Donkey Kong Country&quot; series only had released five games (not counting remakes or ports).",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "In the game &quot;Subnautica&quot;, a &quot;Cave Crawler&quot; will attack you.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "DragonForce&#039;s &#039;Through the Fire and Flames&#039; is widely considered to be the hardest song in the Guitar Hero series.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "The main antagonist in the videogame Saints Row IV is an entity known as The Mastermind.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "POLYBIUS is a myth arcade cabinet\/game", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "In Riot Games &quot;League of Legends&quot; the name of Halloween event is called &quot;The Reckoning&quot;.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "In the game Dead by Daylight, the killer Michael Myers is refered to as &quot;The Shape&quot;.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
         "question": "&quot;Return to Castle Wolfenstein&quot; was the only game of the Wolfenstein series where you don&#039;t play as William &quot;B.J.&quot; Blazkowicz.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
         "question": "Doki Doki Literature Club was developed in Japan.", "correct_answer": "False",
         "incorrect_answers": ["True"]}]
